#! /bin/bash

efibootmgr --create --disk /dev/nvme0n1 --part 1 --label "Void 6.14" --loader /vmlinuz-6.14.0_1 --unicode 'root=UUID=f70e5d1b-bb2d-47b6-b7b4-640d398627aa rw initrd=\initramfs-6.14.0_1.img quiet loglevel=0 audit=0'
efibootmgr --create --disk /dev/nvme0n1 --part 1 --label "Void 6.12" --loader /vmlinuz-6.12.20_1 --unicode 'root=UUID=f70e5d1b-bb2d-47b6-b7b4-640d398627aa rw initrd=\initramfs-6.12.20_1.img quiet loglevel=0 audit=0'
