icon: &icon Inconsolata:pixelsize=20
text: &text Inconsolata:pixelsize=14

bar:
  height: 21
  location: top
  background: 1d2021ff
  foreground: d4be98ff
  spacing: 5
  font: *text

  left:
    - label:
        content: {string: {text: '', foreground: 478061ff, font: *icon}}
    - dwl:
        number-of-tags: 9
        dwl-info-filename: "/home/toby/.cache/dwl_info"
        name-of-tags: ["1","2","3","4","5","6","7","8","9"]
        content:
          list:
            items:
              - map:
                  conditions:
                    # default tag
                    id == 0: {string: {text: "| {layout} | {title}"}}

                    selected:
                      list:
                        items:
                          - map:
                              conditions:
                                id == 1: {string: {text: "󰎤 ", foreground: 478061ff, font: *icon}}
                                id == 2: {string: {text: "󰎧 ", foreground: 478061ff, font: *icon}}
                                id == 3: {string: {text: "󰎪 ", foreground: 478061ff, font: *icon}}
                                id == 4: {string: {text: "󰎭 ", foreground: 478061ff, font: *icon}}
                                id == 5: {string: {text: "󰎱 ", foreground: 478061ff, font: *icon}}
                                id == 6: {string: {text: "󰎳 ", foreground: 478061ff, font: *icon}}
                                id == 7: {string: {text: "󰎶 ", foreground: 478061ff, font: *icon}}
                                id == 8: {string: {text: "󰎹 ", foreground: 478061ff, font: *icon}}
                                id == 9: {string: {text: "󰎼 ", foreground: 478061ff, font: *icon}}

                    ~empty:
                      list:
                        items:
                          - map:
                              conditions:
                                id == 1: {string: {text: "󰎥 ", font: *icon}}
                                id == 2: {string: {text: "󰎨 ", font: *icon}}
                                id == 3: {string: {text: "󰎫 ", font: *icon}}
                                id == 4: {string: {text: "󰎲 ", font: *icon}}
                                id == 5: {string: {text: "󰎯 ", font: *icon}}
                                id == 6: {string: {text: "󰎴 ", font: *icon}}
                                id == 7: {string: {text: "󰎷 ", font: *icon}}
                                id == 8: {string: {text: "󰎺 ", font: *icon}}
                                id == 9: {string: {text: "󰎽 ", font: *icon}}

                    urgent:
                      list:
                        items:
                          - map:
                              conditions:
                                id == 1: {string: {text: "󰲠 ", foreground: ffa600ff, font: *icon}}
                                id == 2: {string: {text: "󰲢 ", foreground: ffa600ff, font: *icon}}
                                id == 3: {string: {text: "󰲤 ", foreground: ffa600ff, font: *icon}}
                                id == 4: {string: {text: "󰲦 ", foreground: ffa600ff, font: *icon}}
                                id == 5: {string: {text: "󰲨 ", foreground: ffa600ff, font: *icon}}
                                id == 6: {string: {text: "󰲪 ", foreground: ffa600ff, font: *icon}}
                                id == 7: {string: {text: "󰲬 ", foreground: ffa600ff, font: *icon}}
                                id == 8: {string: {text: "󰲮 ", foreground: ffa600ff, font: *icon}}
                                id == 9: {string: {text: "󰲰 ", foreground: ffa600ff, font: *icon}}

  right:
      - label:
          content: {string: {text: '|'}}
      - pipewire:
          content:
            map:
              conditions:
                type == sink:
                  map:
                    conditions:
                      muted: {string: {text: 󰖁 , foreground: ffa600ff, font: *icon}}
                      ~muted:
                        ramp:
                          tag: volume
                          items:
                            - string: {text: 󰖀, font: *icon}
                            - string: {text: 󰖀, font: *icon}
                            - string: {text: 󰕾, font: *icon}
      - network:
         # name: wlp194s0
         content:
           map:
             conditions:
               state == down: {string: {text: 󰤭, font: *icon}}
               state == up:
                 ramp:
                   tag: signal
                   items:
                     # - string: {text: 󰤟, font: *icon}
                     - string: {text: 󰤢, font: *icon}
                     - string: {text: 󰤥, font: *icon}
                     - string: {text: 󰤨, font: *icon}
      - battery:
          name: BAT0
          poll-interval: 2000
          anchors:
            discharging: &discharging
              list:
                items:
                  - ramp:
                      tag: capacity
                      items:
                        - string: {text: "󰂃{capacity}%", foreground: ffa600ff, font: *icon}
                        - string: {text: "󰂃{capacity}%", foreground: ffa600ff, font: *icon}
                        - string: {text: 󰁼, font: *icon}
                        - string: {text: 󰁽, font: *icon}
                        - string: {text: 󰁾, font: *icon}
                        - string: {text: 󰁿, font: *icon}
                        - string: {text: 󰂀, font: *icon}
                        - string: {text: 󰂁, font: *icon}
                        - string: {text: 󰂂, font: *icon}
                        - string: {text: 󰁹, font: *icon}
          content:
            map:
              conditions:
                state == unknown:
                  <<: *discharging
                state == discharging:
                  <<: *discharging
                state == "not charging":
                  <<: *discharging
                state == charging:
                  - string: {text: 󰂄, foreground: 00ff00ff, font: *icon}
                  - string: {text: "{capacity}%"}
                state == full:
                  - string: {text: 󱟢, foreground: 00ff00ff, font: *icon}
      - label:
          content: {string: {text: '|'}}
      - clock:
          date-format: "%Y/%m/%d"
          content:
            - string: {text: "{date}", right-margin: 5}
            - string: {text: "{time}"}



