bar:
  height: 20
  location: top
  background: 000000ff
  spacing: 5

  left:
    - label:
        content: {string: {text: ' ', foreground: 478061ff}}
    - dwl:
        number-of-tags: 9
        dwl-info-filename: "/home/toby/.cache/dwl_info"
        name-of-tags: ["1","2","3","4","5","6","7","8","9"]
        content:
          list:
            items:
              - map:
                  conditions:
                    # default tag
                    id == 0: {string: {text: " | {layout} | {title}"}}

                    selected: {string: {text: "[{name}]"}}
                    ~empty: {string: {text: " {name} "}}
                    urgent: {string: {text: " !{name}! ", foreground: ffa600ff}}

  right:
      - label:
          content: {string: {text: '|'}}
      - pipewire:
          content:
            map:
              conditions:
                type == sink:
                  map:
                    conditions:
                      muted: {string: {text: 󰖁 , foreground: ffa600ff}}
                      ~muted:
                        ramp:
                          tag: volume
                          items:
                            - string: {text: 󰖀}
                            - string: {text: 󰖀}
                            - string: {text: 󰕾}
      - network:
         # name: wlp194s0
         content:
           map:
             conditions:
               state == down: {string: {text: 󰤭,}}
               state == up:
                 ramp:
                   tag: signal
                   items:
                     # - string: {text: 󰤟, font: *icon}
                     - string: {text: 󰤢}
                     - string: {text: 󰤥}
                     - string: {text: 󰤨}
      - battery:
          name: BAT0
          poll-interval: 2000
          anchors:
            discharging: &discharging
              list:
                items:
                  - ramp:
                      tag: capacity
                      items:
                        - string: {text: "󰂃{capacity}%", foreground: ffa600ff}
                        - string: {text: "󰂃{capacity}%", foreground: ffa600ff}
                        - string: {text: 󰁼}
                        - string: {text: 󰁽}
                        - string: {text: 󰁾}
                        - string: {text: 󰁿}
                        - string: {text: 󰂀}
                        - string: {text: 󰂁}
                        - string: {text: 󰂂}
                        - string: {text: 󰁹}
          content:
            map:
              conditions:
                state == unknown:
                  <<: *discharging
                state == discharging:
                  <<: *discharging
                state == "not charging":
                  <<: *discharging
                state == charging:
                  - string: {text: 󰂄, foreground: 00ff00ff}
                  - string: {text: "{capacity}%"}
                state == full:
                  - string: {text: 󱟢, foreground: 00ff00ff}
      - label:
          content: {string: {text: '|'}}
      - clock:
          date-format: "%Y/%m/%d"
          content:
            - string: {text: "{date}", right-margin: 5}
            - string: {text: "{time}"}



